//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBChecklist
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchStatus
    {
        public int Id { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> TimeLevel { get; set; }
        public string EOCStage { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
