//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBChecklist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<int> Percentage { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
