//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBChecklist
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLogic
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string state { get; set; }
        public Nullable<int> activeThreadCount { get; set; }
        public Nullable<int> jvmProcessorLoad { get; set; }
        public Nullable<decimal> usedPhysicalMemory { get; set; }
        public Nullable<decimal> heapFreeCurrent { get; set; }
        public Nullable<decimal> heapSizeCurrent { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual Health Health1 { get; set; }
    }
}
